#!/usr/bin/env python
# coding: utf-8

"""Summarize the budget needed to first reach each method's best validation score.

Requires `search_history.csv`, generated by `run_overlap_simulation.py` after
2026-05-12 code update.
"""

from pathlib import Path
import argparse
import math

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


METHOD_ORDER = ["grid", "random", "bayesian", "hyperband", "bohb"]
METHOD_LABELS = {
    "grid": "Grid",
    "random": "Random",
    "bayesian": "Bayesian",
    "hyperband": "Hyperband",
    "bohb": "BOHB",
}
COLORS = {
    "grid": "#4c78a8",
    "random": "#f58518",
    "bayesian": "#54a24b",
    "hyperband": "#b279a2",
    "bohb": "#e45756",
}


def parse_separation(name):
    token = name.split("sep_", 1)[1].split("_", 1)[0]
    return float(token.replace("p", "."))


def parse_outlier_fraction(name):
    token = name.split("ratio_", 1)[1].split("_", 1)[0]
    return float(token.replace("p", "."))


def format_ratio(outlier_fraction):
    normal = int(round((1.0 - outlier_fraction) * 100))
    anomaly = int(round(outlier_fraction * 100))
    return f"{normal}:{anomaly}"


def summarize_one_history(history):
    rows = []
    group_cols = ["repeat", "fold", "method"]
    for (repeat, fold, method), group in history.groupby(group_cols):
        group = group.sort_values("eval_index")
        best_score = group["score"].max()
        first_best = group[group["score"] == best_score].iloc[0]
        if "trial_number" in group.columns and pd.notna(first_best.get("trial_number")):
            trials_to_best = int(first_best["trial_number"]) + 1
        else:
            trials_to_best = int(first_best["eval_index"])
        rows.append({
            "repeat": repeat,
            "fold": fold,
            "method": method,
            "best_score": best_score,
            "evals_to_best": int(first_best["eval_index"]),
            "trials_to_best": trials_to_best,
            "resource_step_at_best": first_best.get("resource_step"),
            "time_to_best_sec": first_best["elapsed_sec"],
            "total_observed_evals": int(group["eval_index"].max()),
            "total_time_sec": group["elapsed_sec"].max(),
        })
    return pd.DataFrame(rows)


def mean_sem(series):
    return pd.Series({
        "mean": series.mean(),
        "sem": series.sem(ddof=1),
    })


def summarize_across_runs(per_fold):
    rows = []
    for method, group in per_fold.groupby("method"):
        row = {"method": method, "method_label": METHOD_LABELS[method]}
        for col in ["evals_to_best", "trials_to_best", "time_to_best_sec", "best_score"]:
            stats = mean_sem(group[col])
            row[f"{col}_mean"] = stats["mean"]
            row[f"{col}_sem"] = stats["sem"]
        rows.append(row)
    out = pd.DataFrame(rows)
    out["method"] = pd.Categorical(out["method"], categories=METHOD_ORDER, ordered=True)
    return out.sort_values("method")


def plot_budget(summary, value_col, ylabel, title, output_path):
    fig, ax = plt.subplots(figsize=(9.2, 5.2))
    summary = summary.sort_values("method")
    labels = summary["method_label"]
    colors = [COLORS[m] for m in summary["method"]]
    bars = ax.bar(labels, summary[value_col], color=colors, alpha=0.9)
    sem_col = value_col.replace("_mean", "_sem")
    if sem_col in summary.columns:
        ax.errorbar(
            range(len(summary)),
            summary[value_col],
            yerr=summary[sem_col],
            fmt="none",
            ecolor="#333333",
            capsize=3,
            linewidth=1,
        )
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(axis="y", linewidth=0.45, alpha=0.35)
    ax.bar_label(bars, labels=[f"{v:.1f}" for v in summary[value_col]], padding=3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent / "Review_Overlap")
    parser.add_argument("--separations", nargs="+", type=float, default=[2.0, 1.25])
    args = parser.parse_args()

    all_per_fold = []
    all_summary = []
    for scenario_dir in sorted(args.root.glob("overlap_*")):
        if not scenario_dir.is_dir():
            continue
        separation = parse_separation(scenario_dir.name)
        if separation not in args.separations:
            continue
        outlier_fraction = parse_outlier_fraction(scenario_dir.name)
        history_path = scenario_dir / "Result" / "search_history.csv"
        if not history_path.exists():
            print(f"Missing search_history.csv: {scenario_dir.name}")
            continue
        history = pd.read_csv(history_path)
        per_fold = summarize_one_history(history)
        per_fold["separation"] = separation
        per_fold["outlier_fraction"] = outlier_fraction
        per_fold["normal_to_anomaly_ratio"] = format_ratio(outlier_fraction)
        per_fold["scenario"] = scenario_dir.name
        summary = summarize_across_runs(per_fold)
        summary["separation"] = separation
        summary["outlier_fraction"] = outlier_fraction
        summary["normal_to_anomaly_ratio"] = format_ratio(outlier_fraction)
        summary["scenario"] = scenario_dir.name
        all_per_fold.append(per_fold)
        all_summary.append(summary)

    if not all_summary:
        raise FileNotFoundError(
            "No search_history.csv files found for the requested separations. "
            "Rerun run_overlap_simulation.py after the search-history update."
        )

    per_fold_all = pd.concat(all_per_fold, ignore_index=True)
    summary_all = pd.concat(all_summary, ignore_index=True)

    per_fold_path = args.root / "budget_to_best_per_fold.csv"
    summary_path = args.root / "budget_to_best_summary.csv"
    per_fold_all.to_csv(per_fold_path, index=False)
    summary_all.to_csv(summary_path, index=False)

    for separation, sep_summary in summary_all.groupby("separation"):
        suffix = str(separation).replace(".", "p")
        plot_budget(
            sep_summary,
            "trials_to_best_mean",
            "Trials to first best score",
            f"Trials to Best Score (separation={separation:g})",
            args.root / f"budget_to_best_trials_sep_{suffix}.png",
        )
        plot_budget(
            sep_summary,
            "time_to_best_sec_mean",
            "Seconds to first best score",
            f"Time to Best Score (separation={separation:g})",
            args.root / f"budget_to_best_time_sep_{suffix}.png",
        )

    print(f"Saved: {per_fold_path}")
    print(f"Saved: {summary_path}")
    print(summary_all.to_string(index=False))


if __name__ == "__main__":
    main()
